name: Main Release
on:
  push:
    branches: [ main ]

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Get Pubspec Version
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version is used
        run: |
          URL=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/tags/${{ steps.get_version.outputs.VERSION }}
          CODE=$(curl -s -H "Authorization: Bearer ${{ github.token }}" -o /dev/null -w "%{http_code}" "$URL")
          if [ "$CODE" != 404 ]; then
            echo "Release 'v${{ steps.get_version.outputs.VERSION }}' already exists. ($CODE)"
            exit 1
          fi

      - name: Dart Environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Dart Pub Get
        run: dart pub get

      - name: Dart Analyze
        run: dart analyze --fatal-infos

      - name: Install lcov
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -y
          sudo apt install -y lcov

      - name: Dart Test
        run: |
          dart test \
          --coverage-path=./coverage/lcov.info \
          --reporter=github \
          --concurrency=$(grep -c processor /proc/cpuinfo)

      - name: Creating Test Coverage HTML
        run: |
          genhtml coverage/lcov.info \
            --output-directory coverage/html/coverage \
            --title "check" \
            --show-details

      - name: Creating package filter.
        run: dart run helpers/create_index.dart README.md coverage/html/index.html

      - name: Publishing to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./coverage/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: check.testainers.com

      - name: Creating a GitHub Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.get_version.outputs.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build ${{ matrix.target }}
    needs: prepare
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target: linux-amd64
            ext: ""
          - runner: ubuntu-24.04-arm
            target: linux-arm64
            ext: ""
          - runner: macos-15-intel
            target: macos-intel
            ext: ""
          - runner: macos-15
            target: macos-silicon
            ext: ""
          - runner: windows-latest
            target: windows-amd64
            ext: ".exe"

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Dart Environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Dart Pub Get
        shell: bash
        run: dart pub get

      - name: Dart Test
        shell: bash
        run: dart test

      - name: Update Version in Code
        shell: bash
        run: dart run helpers/update_version.dart ${{ needs.prepare.outputs.VERSION }}

      - name: Dart Compile
        shell: bash
        run: |
          mkdir -p build
          dart compile exe bin/check.dart -o build/check-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: check-${{ matrix.target }}
          path: build/check-${{ matrix.target }}${{ matrix.ext }}
          retention-days: 1

  release:
    name: Create GitHub Release
    needs: [ prepare, build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.prepare.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: artifacts/*
          generateReleaseNotes: true
