name: Pull Request Tests

on: [ pull_request ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Dart Environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Dart Pub Get
        run: dart pub get

      - name: Dart Analyze
        run: dart analyze --fatal-infos

      - name: Dart Test
        run: |
          dart test \
            --reporter=github \
            --concurrency=$(grep -c processor /proc/cpuinfo)
